# Config to load data from the neuralop package's darcy equation example

name: neuralop_darcy_flow_small
type: package
channels: [vorticity]

package: 
  __target__: neuralop.data.datasets.load_darcy_flow_small
  n_train: 1000 # Number of training snapshots
  batch_size: 64
  n_tests: [100, 50] # Number of testing snapshots per test dataset
  test_resolution: [16, 32] # Grid resolution of test datasets
  test_batch_sizes: [32, 32,] # Number of batches per 
