epochs: 100

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3

dataloader:
  train:
    batch_size: 16
  val:
    batch_size: 16
  test:
    batch_size: 16

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${training.epochs}

artifacts:
  path: artifacts
  save_every: 20 # regular training-state checkpoint interval, in epochs
