# @package _global_
# Usage: uv run python -m fnorollout.scripts.train_fno2d +training_experiments=experiment_2.1
id: 2.1

defaults:
  - /data_sources@data.sources.qg_beta_forced: qg_beta_forced
  - override /data_sources@data.sources.torus2d_example: null # Remove default data source

data:
  split:
    train: 1.0
    val: 0.0

hydra:
  run:
    dir: outputs/training_experiment_${id}
  job:
    chdir: true

wandb:
  name: training_experiment_${id}
  tags: ["multi_trajectory", "single_beta", "forced_beta_turbulence", "no_viscosity", "seed_change_only"]
