# @package _global_
# Usage: uv run python -m fnorollout.scripts.train_fno2d +training_experiments=experiment_2.2
id: 2.2

defaults:
  - /data_sources@data.sources.qg_beta_forced: qg_beta_forced
  - override /data_sources@data.sources.torus2d_example: null # Remove default data source

loss:
  defaults:
    - /loss@training_loss.l2: l2
    - override /loss@training_loss.h1: null

hydra:
  run:
    dir: outputs/training_experiment_${id}
  job:
    chdir: true

wandb:
  name: training_experiment_${id}
  tags: ["multi_trajectory", "single_beta", "forced_beta_turbulence", "no_viscosity", "seed_change_only"]
