"""Sweep simulation parameters of a Julia datagen script (fnorollout/julia/datagen/scripts/)
to generate many trajectory samples, grouped into per-sweep-variable subdirectories
under data/raw/. The total sample count is split equally across sweeps; within a
sweep, values are cycled through and each sample gets a distinct (perturbed) seed, so
a sweep can produce more samples than it has listed values. With no --sweep given at
all, the original config's values are used unchanged and --total-samples trajectories
are generated by perturbing only the seed.

All samples run in a single Julia process (via scripts/run_sweep.jl), so package
loading and CUDA/JIT kernel compilation happen once for the whole run rather than once
per sample.

Usage:
    uv run python -m fnorollout.scripts.generate_ns2d_data \\
        ns2d_torus_vorticity.jl ns2d_torus_vorticity.toml \\
        --sweep initial_condition.grf_tau=3.0,5.0,7.0,10.0 \\
        --sweep numerics.nu=1e-5,1e-4,1e-3,1e-2 \\
        --total-samples 20 \\
        --output-dir ns2d_sweep

    uv run python -m fnorollout.scripts.generate_ns2d_data \\
        ns2d_torus_vorticity.jl ns2d_torus_vorticity.toml \\
        --total-samples 20 \\
        --output-dir ns2d_seed_only
"""

import argparse
import datetime
import random
import shutil
import subprocess
import time
from pathlib import Path

from pydantic import BaseModel

JULIA_DATAGEN_DIR = Path(__file__).resolve().parents[1] / "julia" / "datagen"
DATA_RAW_DIR = Path(__file__).resolve().parents[2] / "data" / "raw"

MAX_SEED = 2**31 - 1  # fits the Int seed type both Julia datagen scripts expect


def format_elapsed(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes, seconds = divmod(seconds, 60)
    return f"{int(minutes)}m {seconds:.1f}s"


def random_seeds(count: int) -> list[int]:
    """Draws `count` unique random seeds"""
    return random.sample(range(MAX_SEED), count)


class SimulationVariableSweep(BaseModel):
    """
    One simulation variable to sweep: a dotted-key config path (matching the Julia
    script's `key.subkey=value` CLI override syntax, e.g. "initial_condition.grf_tau")
    and the list of values to cycle through while generating that sweep's samples.
    """

    variable: str
    values: list[float]


def parse_sweep_arg(raw: str) -> SimulationVariableSweep:
    """Parses a `--sweep` arg of the form `variable=value1,value2,...`."""
    variable, values_spec = raw.split("=", 1)
    values = [float(value) for value in values_spec.split(",")]
    return SimulationVariableSweep(variable=variable, values=values)


def create_sweep_instances(sweep_args: list[str]) -> list[SimulationVariableSweep]:
    return [parse_sweep_arg(arg) for arg in sweep_args]


def sample_counts_per_sweep(num_sweeps: int, total_samples: int) -> list[int]:
    """Splits total_samples as equally as possible across num_sweeps sweeps."""
    if total_samples < num_sweeps:
        raise ValueError(
            f"--total-samples ({total_samples}) must be >= number of sweeps ({num_sweeps})"
        )
    base_share, extra = divmod(total_samples, num_sweeps)
    return [base_share + (1 if i < extra else 0) for i in range(num_sweeps)]


def julia_executable() -> str:
    # Julia isn't always on PATH in non-interactive shells; fall back to juliaup's default location.
    return shutil.which("julia") or str(Path.home() / ".juliaup" / "bin" / "julia")


def build_seed_only_samples(total_samples: int, run_dir: Path) -> list[dict]:
    """No sweep given: keep the base config's values unchanged and generate
    total_samples trajectories that differ only by seed."""
    seed_dir = run_dir / "seed"
    return [
        {"overrides": {"seed": seed}, "output_path": seed_dir / f"seed{seed}.nc"}
        for seed in random_seeds(total_samples)
    ]


def build_sweep_samples(
    sweeps: list[SimulationVariableSweep], total_samples: int, run_dir: Path
) -> list[dict]:
    per_sweep_counts = sample_counts_per_sweep(len(sweeps), total_samples)
    seeds = random_seeds(
        total_samples
    )  # perturbing the seed lets a sweep exceed its listed value count

    samples = []
    sample_index = 0
    for sweep, count in zip(sweeps, per_sweep_counts):
        sweep_dir = run_dir / sweep.variable.replace(".", "_")

        for i in range(count):
            value = sweep.values[i % len(sweep.values)]
            value_label = f"{value:.10g}"
            seed = seeds[sample_index]

            overrides = {sweep.variable: value}
            if sweep.variable != "seed":
                overrides["seed"] = seed

            samples.append(
                {
                    "overrides": overrides,
                    "output_path": sweep_dir / f"{value_label}_seed{seed}.nc",
                }
            )
            sample_index += 1

    return samples


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value) if isinstance(value, float) else str(value)
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_plan(
    plan_path: Path, script: str, config_path: Path, samples: list[dict]
) -> None:
    """
    Writes a TOML plan run_sweep.jl reads: which script/config to use, and each
    sample's config overrides + destination path, so all samples can run in one
    Julia process instead of one subprocess per sample.
    """
    lines = [
        f"script = {_toml_value(script)}",
        f"config = {_toml_value(str(config_path))}",
        "",
    ]
    for sample in samples:
        lines.append("[[samples]]")
        lines.append(f"output_path = {_toml_value(str(sample['output_path']))}")
        lines.append("[samples.overrides]")
        for key, value in sample["overrides"].items():
            lines.append(f"{_toml_value(key)} = {_toml_value(value)}")
        lines.append("")
    plan_path.write_text("\n".join(lines))


def execute_plan(plan_path: Path, total_samples: int, run_dir: Path) -> None:
    run_sweep_script = JULIA_DATAGEN_DIR / "scripts" / "run_sweep.jl"
    run_start = time.perf_counter()
    subprocess.run(
        [
            julia_executable(),
            f"--project={JULIA_DATAGEN_DIR}",
            str(run_sweep_script),
            str(plan_path),
        ],
        cwd=JULIA_DATAGEN_DIR,
        check=True,
    )
    total_elapsed = format_elapsed(time.perf_counter() - run_start)
    print(f"Generated {total_samples} samples under {run_dir} in {total_elapsed}")


def run_sweep(
    script: str,
    config: str,
    sweeps: list[SimulationVariableSweep],
    total_samples: int,
    output_dir: str,
) -> None:
    config_path = JULIA_DATAGEN_DIR / "configs" / config

    # Namespaced by script so two scripts sharing an --output-dir never combine outputs
    run_dir = DATA_RAW_DIR / output_dir / Path(script).stem
    run_dir.mkdir(parents=True, exist_ok=True)

    samples = (
        build_seed_only_samples(total_samples, run_dir)
        if not sweeps
        else build_sweep_samples(sweeps, total_samples, run_dir)
    )

    plan_path = run_dir / "sweep_plan.toml"
    write_plan(plan_path, script, config_path, samples)

    execute_plan(plan_path, len(samples), run_dir)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "script",
        help="Julia datagen script name under julia/datagen/scripts/, e.g. ns2d_data.jl",
    )
    parser.add_argument(
        "config",
        help="Base TOML config name under julia/datagen/configs/, e.g. ns2d_data.toml",
    )
    parser.add_argument(
        "--sweep",
        action="append",
        default=[],
        dest="sweeps",
        metavar="VARIABLE=VALUE[,VALUE...]",
        help="Simulation variable to sweep, e.g. initial_condition.grf_tau=3.0,5.0,7.0 or "
        "numerics.nu=1e-5,1e-4,1e-3,1e-2. Repeatable across variables. Each sweep gets an "
        "equal share of --total-samples; if that share exceeds the number of listed values, "
        "values are cycled through with a different seed each time. If omitted entirely, "
        "the base config's values are used unchanged and samples differ only by seed.",
    )
    parser.add_argument(
        "--total-samples",
        type=int,
        required=True,
        help="Total samples across all sweeps",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Subdirectory under data/raw/ to write samples into (default: '<script>_sweep_<timestamp>')",
    )
    args = parser.parse_args()

    output_dir = (
        args.output_dir
        or f"{Path(args.script).stem}_sweep_{datetime.datetime.now(datetime.UTC):%Y%m%d_%H%M%S}"
    )
    sweeps = create_sweep_instances(args.sweeps)
    run_sweep(
        script=args.script,
        config=args.config,
        sweeps=sweeps,
        total_samples=args.total_samples,
        output_dir=output_dir,
    )


if __name__ == "__main__":
    main()
