defaults:
  - data_sources: qg_beta_forced_test
  - _self_

rollout_steps: 800
start_index: 0

artifacts:
  path: ???
  train_config: config.yaml
  data_processor: data_processor.pt
  model: model_state_dict.pt
  optimizer: optimizer.pt
  scheduler: scheduler.pt

output_path: ???
device: cpu

hydra:
  run:
    dir: outputs/${utcnow:%Y-%m-%d}/${utcnow:%H-%M-%S}
  job:
    chdir: true
